// <auto-generated />
using System;
using HospitalWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729161824_AddDefaultDepartments")]
    partial class AddDefaultDepartments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("HospitalWeb.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "الجراحة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "الباطني"
                        },
                        new
                        {
                            Id = 3,
                            Name = "النسائية"
                        },
                        new
                        {
                            Id = 4,
                            Name = "الأطفال"
                        },
                        new
                        {
                            Id = 5,
                            Name = "الطوارئ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "الاختياري"
                        });
                });

            modelBuilder.Entity("HospitalWeb.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImagePath");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone");

                    b.Property<string>("الاسم")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("الاسم");

                    b.Property<string>("الجامعة")
                        .HasColumnType("TEXT")
                        .HasColumnName("الجامعة");

                    b.Property<string>("الجنس")
                        .HasColumnType("TEXT")
                        .HasColumnName("الجنس");

                    b.Property<string>("الرقم_الوطني")
                        .HasColumnType("TEXT")
                        .HasColumnName("الرقم_الوطني");

                    b.Property<DateTime?>("تاريخ_الميلاد")
                        .HasColumnType("TEXT")
                        .HasColumnName("تاريخ_الميلاد");

                    b.Property<string>("رقم_الطبيب")
                        .HasColumnType("TEXT")
                        .HasColumnName("رقم_الطبيب");

                    b.Property<int?>("سنة_التخرج")
                        .HasColumnType("INTEGER")
                        .HasColumnName("سنة_التخرج");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalWeb.Models.TrainingRotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId");

                    b.ToTable("TrainingRotations");
                });

            modelBuilder.Entity("HospitalWeb.Models.TrainingRotation", b =>
                {
                    b.HasOne("HospitalWeb.Models.Department", "Department")
                        .WithMany("TrainingRotations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalWeb.Models.Doctor", "Doctor")
                        .WithMany("TrainingRotations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HospitalWeb.Models.Department", b =>
                {
                    b.Navigation("TrainingRotations");
                });

            modelBuilder.Entity("HospitalWeb.Models.Doctor", b =>
                {
                    b.Navigation("TrainingRotations");
                });
#pragma warning restore 612, 618
        }
    }
}
