// <auto-generated />
using System;
using HospitalWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729163712_AddUniqueDoctorDepartment")]
    partial class AddUniqueDoctorDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("HospitalWeb.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HospitalWeb.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImagePath");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone");

                    b.Property<string>("الاسم")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("الاسم");

                    b.Property<string>("الجامعة")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("الجامعة");

                    b.Property<string>("الجنس")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("الجنس");

                    b.Property<string>("الرقم_الوطني")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("الرقم_الوطني");

                    b.Property<DateTime?>("تاريخ_الميلاد")
                        .HasColumnType("TEXT")
                        .HasColumnName("تاريخ_الميلاد");

                    b.Property<string>("رقم_الطبيب")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("رقم_الطبيب");

                    b.Property<int?>("سنة_التخرج")
                        .HasColumnType("INTEGER")
                        .HasColumnName("سنة_التخرج");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalWeb.Models.TrainingRotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("TrainingRotations");
                });

            modelBuilder.Entity("HospitalWeb.Models.TrainingRotation", b =>
                {
                    b.HasOne("HospitalWeb.Models.Department", "Department")
                        .WithMany("TrainingRotations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalWeb.Models.Doctor", "Doctor")
                        .WithMany("TrainingRotations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HospitalWeb.Models.Department", b =>
                {
                    b.Navigation("TrainingRotations");
                });

            modelBuilder.Entity("HospitalWeb.Models.Doctor", b =>
                {
                    b.Navigation("TrainingRotations");
                });
#pragma warning restore 612, 618
        }
    }
}
