// <auto-generated />
using System;
using HospitalWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalWeb.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "الجراحة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "الباطني"
                        },
                        new
                        {
                            Id = 3,
                            Name = "النسائية"
                        },
                        new
                        {
                            Id = 4,
                            Name = "الأطفال"
                        },
                        new
                        {
                            Id = 5,
                            Name = "الطوارئ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "الاختياري"
                        });
                });

            modelBuilder.Entity("HospitalWeb.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("ImagePath");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("الاسم")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("الاسم");

                    b.Property<string>("الجامعة")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("الجامعة");

                    b.Property<string>("الجنس")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("الجنس");

                    b.Property<string>("الرقم_الوطني")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("الرقم_الوطني");

                    b.Property<DateTime?>("تاريخ_المباشرة")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("تاريخ_المباشرة");

                    b.Property<DateTime?>("تاريخ_الميلاد")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("تاريخ_الميلاد");

                    b.Property<string>("رقم_الطبيب")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("رقم_الطبيب");

                    b.Property<int?>("سنة_التخرج")
                        .HasColumnType("integer")
                        .HasColumnName("سنة_التخرج");

                    b.Property<string>("مكان_المباشرة")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("مكان_المباشرة");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalWeb.Models.TrainingRotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("TrainingRotations");
                });

            modelBuilder.Entity("HospitalWeb.Models.TrainingRotation", b =>
                {
                    b.HasOne("HospitalWeb.Models.Department", "Department")
                        .WithMany("TrainingRotations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalWeb.Models.Doctor", "Doctor")
                        .WithMany("TrainingRotations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HospitalWeb.Models.Department", b =>
                {
                    b.Navigation("TrainingRotations");
                });

            modelBuilder.Entity("HospitalWeb.Models.Doctor", b =>
                {
                    b.Navigation("TrainingRotations");
                });
#pragma warning restore 612, 618
        }
    }
}
